=== jmballe/Store/src/main/resources/XML-XSD/Customer.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="customers" type="customersType"/>
    <xs:complexType name="customerType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="email"/>
            <xs:element type="xs:string" name="address"/>
        </xs:sequence>
        <xs:attribute type="xs:integer" name="customer_id"/>
    </xs:complexType>
    <xs:complexType name="customersType">
        <xs:sequence>
            <xs:element type="customerType" name="customer" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== jmballe/Store/src/main/resources/XML-XSD/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Customer.xsd">
    <customer customer_id="6">
        <name>Lionel Richie</name>
        <email>LRich@gmail.com</email>
        <address>430 Heather Sees Way,Skedee,KO</address>
    </customer>
    <customer customer_id="7">
        <name>Gloria Gaynor</name>
        <email>Ggnor@gmail.com</email>
        <address>1102 Kennedy Court,Bedford,MA</address>
    </customer>
</customers>
